[package]
name = "meta-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { path = "../protocol" }
structopt = "0.3"
futures = "0.3"
tokio = {version = "^1.10", features = ["net", "macros", "rt-multi-thread"]}
tokio-util = { version = "0.6", features = ["codec"] }
tokio-serde = { version = "0.8", features = ["bincode"] }

